name: ci

on:
  push:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Install Dependencies
        run: npm install

      - name: Generate Static Project
        run: npm run generate
